# Change these first
owner: BaileyStudio # Your GitHub username
repo: Monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Bailey Stdio
    url: https://www.bailey.studio
  - name: Warranty.Buildsafe.co.uk
    url: https://warranty.buildsafe.co.uk
 

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.bailey.studio
  logoUrl: http://bailey.studio/assets/images/logo/bs@2x.png
  name: 
  introTitle: "**Status Monitor** powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: Bailey Studio
      href: https://www.bailey.studio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
